---
#tasks file for wordpress-server
- name: install apache2
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
  - apache2
  - git
  - php5
  - php5-mysql 
  - libapache2-mod-php5 
  - php5-mcrypt
  - unzip

- name: create directories for log files
  file:
    path: /var/log/apache2/{{ item }}
    state: directory
    mode: 0755
  with_items: 
  - "{{ websites }}"
  notify:
  - restart apache2

## Create directories for log files where the site will redirect to another
- name: create directories for log files
  file:
    path: /var/log/apache2/{{ item.from_site }}
    state: directory
    mode: 0755
  with_items:
  - "{{ alias_websites }}"
  notify:
  - restart apache2


- name: enable mod rewrite
  apache2_module: name=rewrite state=present
  notify:
  - restart apache2

- name: enable mod expires
  apache2_module: name=expires state=present
  notify:
  - restart apache2


- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ item }}.conf
  with_items: 
  - "{{ websites }}"
  notify:
  - restart apache2


- name: create virtual host file for redirects 
  template: src=virtualhost_redirect.conf dest=/etc/apache2/sites-available/"{{ item.from_site }}".conf
  with_items:
  - "{{ alias_websites }}"
  notify:
  - restart apache2


- name: create directories for websites
  file:
    path: /var/www/{{ item }}
    state: directory
    mode: 0755
  with_items: 
  - "{{ websites }}"
  notify:
  - restart apache2

##This uploads a zip if it exists and if there isn't already a wp-config.php at the destination
## {{ role_path }} gives the path to the directory where the role is ie full path

- name: see if the zips exist
  local_action: stat path={{ role_path }}/files/{{ item }}.zip
  with_items:
  - "{{ websites }}"
  register: st

- name: upload and unzip website contents if they exist
  unarchive:
    src: "{{ role_path }}/files/{{ item.item }}.zip"
    dest: /var/www/{{ item.item }}
    creates: /var/www/{{ item.item }}/wp-config.php
  with_items: "{{ st.results }}"
  when: item.stat.exists

- name: Replace db host in wp-config with the RDS instance
  lineinfile: 
    path: /var/www/{{ item }}/wp-config.php
    regexp: "define.*DB_HOST.*localhost"
    backrefs: yes #this way if the line is found it is NOT APPENDED, which is the default
    line: "define('DB_HOST', '{{ db_host }}');"
  with_items: 
    - "{{ websites }}"
  notify:
    - restart apache2

- name: change ownership of all to www-data
  file: 
    dest: /var/www/
    owner: www-data
    group: www-data
    recurse: yes
  notify:
    - restart apache2


- name: a2ensite all sites
  command: a2ensite {{ item }}
  with_items: 
  - "{{ websites }}"
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}.conf
  notify: 
  - restart apache2

- name: a2ensite redirected sites
  command: a2ensite {{ item.from_site }}
  with_items:
  - "{{ alias_websites }}"
  args:
    creates: /etc/apache2/sites-enabled/{{ item.from_site }}.conf
  notify:
  - restart apache2

